trigger:
- Development

pool:
  vmImage: 'ubuntu-latest'

steps:
# 1. Lint HTML files using HTMLHint
- script: |
    npm install htmlhint
    npx htmlhint "src/**/*.html" --config .htmlhintrc
  displayName: 'Lint HTML Files'

# 2. Check PHP syntax using PHP linter
- script: |
    find . -name "*.php" -exec php -l {} \;
  displayName: 'PHP syntax check'


# 3. Package HTML and PHP files into a ZIP archive
- script: |
    if [ -d "src" ]; then
      mkdir -p $(Build.ArtifactStagingDirectory)
      cp -R src/* $(Build.ArtifactStagingDirectory)/
      cd $(Build.ArtifactStagingDirectory)
      zip -r output.zip .
    else
      echo "Directory 'src' does not exist or is empty."
      exit 1
    fi
  displayName: 'Package Files into ZIP'




# 4. Publish the ZIP file as an artifact
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/output.zip'
    artifactName: 'html-php-package'
    publishLocation: 'pipeline'
  displayName: 'Publish ZIP Artifact'


